server:
  port: 8763
spring:
  application:
    name: order-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true 
management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  name: "{cipher}b335bebd5879eb3c21849430ded6bdb4269fc7938dbeb508f665b58e69684db9"
